### PR TITLE
Mock data in files, own mockserver

### PR DESCRIPTION
**Pull request by catenocrypt**
Continuation of PR #1094 

Summary of changes:
- All mock response files are now stored in json files, in `mock/ext-api-data`.
- Mock data files and their URLs are listed in file `mock/datafiles.yaml`
- There is new simple go mockerserver, to server requests from files
- Dyson and JS files dropped
- /Response files can be updated/

### CODE REVIEW

**Comment by EnoRage** [comment]
👍Better than before
Just want to ask, can we use .json file for routes and have readable names for mock files.

Like:
`{PLATFORM}_{API_NAME}_{API_REQUEST}.json`
Example:
`binance_rpc_tokens.json`

Also paths file:
```
[
 {
  "path_to_file": "get/binance_rpc_tokens.json",
  "http_path": "/v1/tokens",
  "method": "GET"
 }, 
...
]
```

**Comment by catenocrypt** [comment]
Have you checked the current filenames?  They are like you wish:

```
- file: mock/ext-api-data/cosmos-api_staking_pool.json
  mockURL: /mock/cosmos-api/staking/pool
  extURL: https://api.cosmos.network/staking/pool
```

I can use JSON instead of YAML -- I like YAML because you can have comments in it.
Field names I can also change, also can add method.  Get/post subfolders do not make sense any more, I got rid of them.

**Comment by catenocrypt** [comment]
TODO: READMEs

**Comment by EnoRage** [comment]
@catenocrypt can we finish this PR today?

**Comment by EnoRage** [comment]
Can we have a file with a normal readable name instead of

aeternity-api_middleware_transactions_account_ak_2WGWYMgWy1opZxgA8AVzGCTavCQyUBtbKx5SrCX6E4kmDZMtJb.json
?

Also can we minify jsons at repo?

**Comment by EnoRage** [comment]
> Have you checked the current filenames? They are like you wish:
> 
> ```
> - file: mock/ext-api-data/cosmos-api_staking_pool.json
>   mockURL: /mock/cosmos-api/staking/pool
>   extURL: https://api.cosmos.network/staking/pool
> ```
> 
> I can use JSON instead of YAML -- I like YAML because you can have comments in it.
> Field names I can also change, also can add method. Get/post subfolders do not make sense any more, I got rid of them.

I think that comments are useless for such thinks like mocks. We need architecte so simple that we do not need comments for that

**Comment by catenocrypt** [comment]
I think this PR can be merged now.
I have updated READMEs, and reduced the large data files.
Outstanding issue is to change filelist yaml to json, but that's quite straightforward, local change, let's not wait for it now.

**Pull request merged**
