### PR TITLE
Update swagger files and readme

### PR DESCRIPTION
**Pull request by hewigovens**
Changes:

- Add `go-swagger` usage, view api docs without running blockatlas
- Run `make go-gen-docs`

### CODE REVIEW

**Comment by EnoRage** [comment]
New docs doesn’t have v2/ endpoint and xpub endpoint

**Comment by hewigovens** [comment]
that's weird, annotations are gone?

**Comment by EnoRage** [comment]
> that's weird, annotations are gone?

Yep, it is the legacy of old api architecture

**Comment by hewigovens** [comment]
removed legacy v1 docs

**Comment by EnoRage** [comment]
I think we still need old swagger docs, let's just keep the info about new command

**Comment by EnoRage** [comment]
We need to have /v1, /v2 docs

**Comment by hewigovens** [comment]
@EnoRage v1 docs are back, just update some ids

**Pull request merged**
