### PR TITLE
add sync command

### PR DESCRIPTION
**Pull request by Pantani**
- Add command to start to sync all market and rate prices
test:
`go run main.go sync-markets`
or
`make start-sync-markets`

- Update cron lib to the latest

### CODE REVIEW

**Comment by madcake** [comment]
What is the motivation to make this сфдд?

**Comment by Pantani** [comment]
> What is the motivation to make this call?

do you mean this PR?

**Comment by madcake** [comment]
> > What is the motivation to make this call?
> 
> do you mean this PR?

I mean go run main.go sync

**Comment by Pantani** [comment]
> > > What is the motivation to make this call?
> > 
> > 
> > do you mean this PR?
> 
> I mean go run main.go sync

to start to sync the market data and prices. I going to change the name, I agree, it's not intuitive,

**Pull request merged**
