### PR TITLE
Split platform files per API implementation

### PR DESCRIPTION
**Pull request by Pantani**
Split platform files per API implementation:

- `base.go` for platform base implementation
- `transaction.go` for tx and token tx API's
- `block.go` for block observer
- `stake.go` for naming service API's
- `token.go` for Token API's
- `collection.go` for Collection API's
- `domain.go` for naming service API's

closes https://github.com/trustwallet/blockatlas/issues/715

### CODE REVIEW

**Comment by vikmeup** [comment]
address.go? What does this mean? transaction.go or transactions.go would be self explanatory 

What is xpub addresses?

**Comment by vikmeup** [comment]
Why base? Is is transaction or block API?

**Comment by Pantani** [comment]
> address.go? What does this mean? transaction.go or transactions.go would be self explanatory
> 
> What is xpub addresses?

https://github.com/trustwallet/blockatlas/blob/master/pkg/blockatlas/api.go#L45

**Comment by Pantani** [comment]
> Why base? Is is transaction or block API?

Is the both, transactions and block, this is the base methods all coins need to implement before implementing other features

**Comment by vikmeup** [comment]
Block is not requires, many blockchains don't have it implemented

**Comment by vikmeup** [comment]
> But I think is weird as well, do you have another suggestion for a name?

transaction.go is a good name. all it does - return transaction list

**Comment by vikmeup** [comment]
@Pantani can you rebase? let's get this merged

**Comment by Pantani** [comment]
> Looks good! much more organized
> 
> You used to have `custom.go` - was not able to find that in the changes

The only custom route we have now is transactions for bitcoin, I put the `v1/xpub` and `v1/address` inside `transaction.go` to be more clear, but I going to put inside the developer documentation in case we need custom routes, create a `custom.go` file

**Pull request merged**
