### PR TITLE
switch to binance mainnet

### PR DESCRIPTION
**Pull request by hewigovens**

### CODE REVIEW

**Comment by vikmeup** [comment]
@hewigovens https://github.com/TrustWallet/blockatlas/blob/master/coin/slip44.go#L214 you can change this decimal and use this parameter in the code for consistency?

**Comment by hewigovens** [comment]
still need to fix the test

**Comment by hewigovens** [comment]
The binance test is failed because the `Value` is decoded as "1"
image

**Comment by kolya182** [comment]
> The binance test is failed because the `Value` is decoded as "1"
> image

`json.Unmarshal` converts `"0.01"` => `"1"` but `"1"` => `"1"` and `"10"` => `"10"` converted as expected. At first i thought it because of type mismatched https://github.com/TrustWallet/blockatlas/pull/74/commits/640d5d28d35d1509e9edcad910c8179963fdbb39 but this is something else causing

**Comment by terorie** [comment]
Will be implemented by #58

**Comment by terorie** [comment]
@hewigovens Thanks for the fixes, I rebased onto newest master in #75. Everything in this PR is implemented, so feel free to delete the branch

**Comment by hewigovens** [comment]
@terorie 👍，I'm still confused why the test was passed locally but failed in CI

**Comment by terorie** [comment]
@hewigovens The import path was wrong. CI had `trust-wallet/blockatlas` instead of `trustwallet/blockatlas`

**Pull request closed without merging**
