### PR TITLE
DONTMERGE Move mock test data files to separate json files

### PR DESCRIPTION
**Pull request by catenocrypt**
Summary of changes:
- All mock response files are now stored in json files, in `mock/ext-api-data`.  
- Response files can be updated, either by 'curl URL > file' or better, by `go run testdatatool.go updateall .`
- Dyson scripts only register to paths and return right file.  They could be now replaces by a simple go http server, listening to all paths, finding corresponding response file and delivering it (this will be next step).

### CODE REVIEW

**Comment by catenocrypt** [comment]
Ready for review.

Summary of changes:
- All mock response files are now stored in json files, in `mock/ext-api-data`.  
- Response files can be updated, either by 'curl URL > file' or better, by `go run testdatatool.go updateall .`
- Dyson scripts only register to paths and return right file.  They could be now replaces by a simple go http server, listening to all paths, finding corresponding response file and delivering it (this will be next step).

For review:
- Tons of response data files and script files are meaningless to review
- Important is the newman tests pass.  Newman tests were not touched
- Have a look at `mock/ext-api-data/README.md`
- Have a glance at `mock/ext-api-data/testdatatool.go`

**Comment by EnoRage** [comment]
Looks better!
Can we have normal names for mock json files?

**Comment by EnoRage** [comment]
basically we need to have only https://github.com/trustwallet/blockatlas/tree/ar/mocktestdata/mock/ext-api-dyson/get 
files there. I do not see any sense to have double code, seems difficult for me

**Comment by catenocrypt** [comment]
> Looks better!
> Can we have normal names for mock json files?

The filenames correspond to the URL path; and to be able to use as filenames, URLEncoded.

```
Filename:   mock%2Fravencoin-api%2Fv2%2Faddress%2FRGkwvrUors8DtmhKy5bddFwRCTZaunjpvo%3Fdetails%3Dtxs.json
Mock URL:   mock/ravencoin-api/v2/address/RGkwvrUors8DtmhKy5bddFwRCTZaunjpvo?details=txs
```

**Comment by EnoRage** [comment]
Most preferable way to make new mocks:
1. Create new json file
2. Add route and path to that file at 1 place

**Comment by EnoRage** [comment]
For it current solution is just more complicated than it was before

**Comment by catenocrypt** [comment]
Last unit test failed with a timeout, non-PR-related :(

**Comment by catenocrypt** [comment]
> Most preferable way to make new mocks:
>     1. Create new json file
>     2. Add route and path to that file at 1 place

Currently it's only one step:
1. Create new json file with naming convention

But I agree that URLencoding the path is a uncomfortable.

If you prefer an extra central place to map request URLs to data file names, that's also possible.

> For it current solution is just more complicated than it was before

Help me simplify it :)

**Comment by EnoRage** [comment]
1. remove any autogen
2. remove all js files except dyson init and path setup (1 js file)

**Comment by prazd** [comment]
`mock%2Fcosmos-api%2Ftxs%3Flimit%3D25%26message.sender%3Dcosmos1dx27g0kzhwej0ekcf2k9hsktcxnmpl7fcehcvq%26page%3D1.json` and `324 000+` lines changed
Are you serious?)

**Comment by catenocrypt** [comment]
Continued in PR #1100 .  All Dyson files removed.

**Comment by catenocrypt** [comment]
> `mock%2Fcosmos-api%2Ftxs%3Flimit%3D25%26message.sender%3Dcosmos1dx27g0kzhwej0ekcf2k9hsktcxnmpl7fcehcvq%26page%3D1.json` and `324 000+` lines changed
> Are you serious?)

These are response data files retrieved from an external API, and stored for the mock tests.  Of course, the content does not to be reviewed :)
But you are right, placing such files in repo is not a godd idea, just for size.
I have reduced them now (by using appropriate parameters in the external source API call (pageSize), not just manually editing, so later refresh will also keep the same format).

**Pull request closed without merging**
