### PR TITLE
Add CODEOWNERS

### PR DESCRIPTION
**Pull request by kolya182**

### CODE REVIEW

**Comment by hewigovens** [comment]
probably https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners makes more sense?

**Comment by kolya182** [comment]
> probably https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners makes more sense?

Changed to CODEOWNERS, let see how we like it.

**Comment by vikmeup** [comment]
What is the purpose of CODEOWNERS ?

**Comment by kolya182** [comment]
> What is the purpose of CODEOWNERS ?

1. Avoid running action
2. Automate assigning more people to take a look at changes
3. Less code vs action ?

**Comment by vikmeup** [comment]
Why not just use one line as suggested in the documentation:
```
* @EnoRage @catenocrypt @hewigovens @kolya182 @prazd
```

**Pull request merged**
