### PR TITLE
WIP Lending API prototype

### PR DESCRIPTION
**Pull request by catenocrypt**
Standalone prototype for Lending API, WIP, #1112 .

### CODE REVIEW

**Comment by EnoRage** [comment]
Cannot understand why do you have mocks? I think, that the most important part of compound research is using real api / contracts to fetch data. Isn’t it?

**Comment by EnoRage** [comment]
https://github.com/bonedaddy/go-compound

**Comment by EnoRage** [comment]
We need:
1. Get information about each Ctoken data (APR, min amount, etc). to supply
2. Get information about already supplied ctoken for specific address

That’s it

**Comment by EnoRage** [comment]
Screenshot 2020-05-30 at 03 40 15
We need to fetch that data

**Comment by catenocrypt** [comment]
The mock is just a temporary, a scaffolding to get a better grip on the API.

The structure is:
- Client to connect to Compound API
- Compound Provider having an internal API, using the client
- API exposing lending API, routing to provider (only one for now), doing some normalization
Very similar to other providers in blockatlas.

**Pull request closed without merging**
