### PR TITLE
Mockserver: -update option to update data files from external services.

### PR DESCRIPTION
**Pull request by catenocrypt**
mockserver -update   updates all external data files with ExtURL set, from external services

### CODE REVIEW

**Comment by EnoRage** [comment]
What is the reason to do it?

**Comment by catenocrypt** [comment]
Sometimes it happens that external service changes, or we switch to new version of it, like when @kolya182 had to manually change the data files due to binance API.  This is a utility to do it automatically; of course updated files have to be tested and reviewed.

**Comment by EnoRage** [comment]
> Sometimes it happens that external service changes, or we switch to new version of it, like when @kolya182 had to manually change the data files due to binance API. This is a utility to do it automatically; of course updated files have to be tested and reviewed.

You just need to paste new json into file for that. If it doesn’t works like that - it must. Because it was discussed previously

**Comment by catenocrypt** [comment]
Closing, baffled.

**Pull request closed without merging**
