### PR TITLE
Add support to Heroku review apps

### PR DESCRIPTION
**Pull request by Pantani**
closes https://github.com/trustwallet/blockatlas/issues/734

### CODE REVIEW

**Comment by vikmeup** [comment]
Why?

**Comment by Pantani** [comment]
> Why? 😢
> 
> Did you test it?

I need to merge this into the `app.json` into the master to can create a pipeline, but I don't have permission inside Heroku to create one. This task is only to add the support, we can create the pipeline and tracking in another one issue below

https://github.com/trustwallet/blockatlas/issues/692

**Comment by vikmeup** [comment]
What's the purpose of this PR then?

**Comment by Pantani** [comment]
> What's the purpose of this PR then?

Add the same base configuration for app reviews, the add-on logentry 

> What does it needs to be on master to test?

To test one-button deploy inside my personal Heroku and test the pipeline creation per PR (#692)

> Where did you get that information from?

https://devcenter.heroku.com/articles/github-integration-review-apps

**Pull request merged**
