### PR TITLE
Fix Kava denom filter

### LINKED ISSUE #1364: [Kava] Denom filter fails on delegation message
When filter by denom should check for different message types

### PR DESCRIPTION
**Pull request by vcoolish**
Fixes #1364

### CODE REVIEW

**Review by hewigovens — COMMENTED** [review]
I assume cosmos has same issue?

**Comment by vcoolish** [comment]
> I assume cosmos has same issue?

We don't have cosmos tokens support

**Comment by hewigovens** [comment]
don't merge this yet, will fix this first: https://github.com/trustwallet/blockatlas/issues/1347

**Review by hewigovens — APPROVED** [review]

**Comment by hewigovens** [comment]
@vcoolish kava might not update to stargate at the same time, let's merge this then do cosmos stargate first

**Pull request merged**
