### PR TITLE
Update Elrond integration

### PR DESCRIPTION
**Pull request by miiu96**
Update Elrond integration to work with the latest version of Elrond Proxy - slight adjustments with respect to the new format of the API responses.

### CODE REVIEW

**Comment by prazd** [comment]
@maxUo 
Could you take a look what's wrong with ` Login to DockerHub Registry` step?

**Comment by maxUo** [comment]
> @maxUo
> Could you take a look what's wrong with ` Login to DockerHub Registry` step?

I'll take a look at this issue soon.

**Comment by EnoRage** [comment]
@maxUo please, help us with the pipeline today

**Comment by maxUo** [comment]
> @maxUo please, help us with the pipeline today

Check #1173

**Comment by maxUo** [comment]
@miiu96 pls checkout master branch

**Comment by EnoRage** [comment]
@miiu96 can you please checkout to the latest master branch, we cannot change your pr. Sorry for some problems on our side before

**Comment by miiu96** [comment]
> @miiu96 can you please checkout to the latest master branch, we cannot change your pr. Sorry for some problems on our side before

Hello. I updated branch but i still have some problems... Maybe you can give me more indications please.

**Comment by rotstall** [comment]
> > @miiu96 can you please checkout to the latest master branch, we cannot change your pr. Sorry for some problems on our side before
> 
> Hello. I updated branch but i still have some problems... Maybe you can give me more indications please. Build still failing.

@miiu96 Please update the branch again.

**Comment by EnoRage** [comment]
Can you also take a look at GetBlockByNumber()

If you will try to run it - you will constantly have errors.

Fast way to run it:
You need to change config to elrond, and you need to have a docker installed

1. make start-docker-services
2. cd cmd/worker
3. go run main.go

**Comment by miiu96** [comment]
> Can you also take a look at GetBlockByNumber()
> 
> If you will try to run it - you will constantly have errors.
> 
> Fast way to run it:
> You need to change config to elrond, and you need to have a docker installed
> 
>     1. make start-docker-services
> 
>     2. cd cmd/worker
> 
>     3. go run main.go

Hello I successfully reproduced this error .... There are to many requests to our database. I'm not sure what is the best fix for this. If you want to work correctly **fetchBlocksInterval** should be increased.

**Pull request merged**
