### PR TITLE
fix panic error

### PR DESCRIPTION
**Pull request by Pantani**
Close [162](https://github.com/trustwallet/backend/issues/162)

### CODE REVIEW

**Comment by kolya182** [comment]
@Pantani  Use "close" word in from of PR link to close it automatically once PR merged.

**Comment by Pantani** [comment]
@kolya182, thks for the tip. But this issue is inside the back-end repository.

**Comment by Pantani** [comment]
@kolya182 the panic is about we try to call a method to log an error without an error object. But I fix in this PR

**Comment by kolya182** [comment]
> @kolya182, thks for the tip. But this issue is inside the back-end repository.

I know, that why i did not expose user request that cause a panic, was curious what was special about it ?

**Pull request merged**
