### PR TITLE
fix bnb fee

### PR DESCRIPTION
**Pull request by Pantani**

### CODE REVIEW

**Comment by Pantani** [comment]
> Maybe we should add handling in `DecimalExp` itself?
> 
> Unit test for this would be useful

we already have, but it doesn't complain about the `.` after the zero

**Comment by vikmeup** [comment]
Where is the `0.` come from?

**Comment by Pantani** [comment]
> Where is the `0.` come from?

when the `srcTx.Fee` is zero, the `DecimalExp` format the fee to `0.`

**Comment by Pantani** [comment]
I'm going merge because we need that, we can improve later

**Comment by vikmeup** [comment]
Can we add test case for `DecimalExp` to handle this? it sounds like a bug inside `DecimalExp` itself

**Pull request merged**
