### PR TITLE
Implement reverse lookup for ENS/FIO

### PR DESCRIPTION
**Pull request by hewigovens**
part of #1018 

- [ ] mock tests

ENS:

`/ns/reverse?coin=60&address=0xC36edF48e21cf395B206352A1819DE658fD7f988`

```json
[
  {
    "result": "ohmyname.eth",
    "coin": 60
  }
]
```

FIO:

`ns/reverse?coin=235&address=FIO6XKiobBGrmPZDaHne47TF25CamjFc3cRe8hs7oAiCN59TbJzes`

```json
[
  {
    "result": "ip@trust",
    "coin": 235
  },
  {
    "result": "pimptee@trust",
    "coin": 235
  }
]
```

### CODE REVIEW

**Comment by catenocrypt** [comment]
Excellent!

Caching will be needed, because this may be a high-traffic API.  Most of the request will be negative (no name found), I think those should be cached as well (with a rel. short expiry).

Mocked tests I can add (after this PR).

One issue: FIO can potentially handle any kind of address, but I think in this impl. only FIO addresses will be attempted (NamingAPIs map).  If so, this should be changed.

**Comment by hewigovens** [comment]
This is mainly for receiving screen in apps, you share your ETH/FIO address

**Comment by catenocrypt** [comment]
> This is mainly for receiving screen in apps, you share your ETH/FIO address

Also for transaction history view.

**Comment by hewigovens** [comment]
Will reopen it when app really needs it

**Pull request closed without merging**
